// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateApplication(arg1) {
  return window['go']['main']['App']['CreateApplication'](arg1);
}

export function CreateInterview(arg1) {
  return window['go']['main']['App']['CreateInterview'](arg1);
}

export function CreateQAItem(arg1) {
  return window['go']['main']['App']['CreateQAItem'](arg1);
}

export function DeleteApplication(arg1) {
  return window['go']['main']['App']['DeleteApplication'](arg1);
}

export function DeleteInterview(arg1) {
  return window['go']['main']['App']['DeleteInterview'](arg1);
}

export function DeleteQAItem(arg1) {
  return window['go']['main']['App']['DeleteQAItem'](arg1);
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function GetApplication(arg1) {
  return window['go']['main']['App']['GetApplication'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function ListApplications() {
  return window['go']['main']['App']['ListApplications']();
}

export function ListInterviews(arg1) {
  return window['go']['main']['App']['ListInterviews'](arg1);
}

export function UpdateApplication(arg1, arg2) {
  return window['go']['main']['App']['UpdateApplication'](arg1, arg2);
}

export function UpdateApplicationStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateApplicationStatus'](arg1, arg2);
}

export function UpdateInterview(arg1, arg2) {
  return window['go']['main']['App']['UpdateInterview'](arg1, arg2);
}

export function UpdateQAItem(arg1, arg2) {
  return window['go']['main']['App']['UpdateQAItem'](arg1, arg2);
}
