// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateApplication(arg1:main.ApplicationInput):Promise<main.Application>;

export function CreateInterview(arg1:main.InterviewInput):Promise<main.Interview>;

export function CreateQAItem(arg1:main.QAItemInput):Promise<main.QAItem>;

export function DeleteApplication(arg1:number):Promise<void>;

export function DeleteInterview(arg1:number):Promise<void>;

export function DeleteQAItem(arg1:number):Promise<void>;

export function ExportData():Promise<string>;

export function GetApplication(arg1:number):Promise<main.Application>;

export function GetStats():Promise<main.Stats>;

export function ListApplications():Promise<Array<main.Application>>;

export function ListInterviews(arg1:number):Promise<Array<main.Interview>>;

export function UpdateApplication(arg1:number,arg2:main.ApplicationInput):Promise<main.Application>;

export function UpdateApplicationStatus(arg1:number,arg2:string):Promise<main.Application>;

export function UpdateInterview(arg1:number,arg2:main.InterviewInput):Promise<main.Interview>;

export function UpdateQAItem(arg1:number,arg2:main.QAItemInput):Promise<main.QAItem>;
